import type { Metadata } from 'next';
import { HeartHandshake, Users, CalendarDays, Sprout, Check, ArrowUpRight, Phone } from 'lucide-react';
import { PageIntro, Eyebrow } from '@/components/shared';
import { contact } from '@/lib/content';
export const metadata: Metadata = { title: 'Careers', description: 'Bring your caring heart to Sisi Care. Learn about caregiving work supporting seniors and adults in Bellevue and the Eastside.' };
export default function Careers() { return <>
 <PageIntro eyebrow="CAREERS AT SISI CARE" title="Bring your caring heart." emphasis="Make someone’s day." description="The everyday things you do can mean everything to someone else. Join a local team helping seniors and adults feel more at home." />
 <section className="section"><div className="container"><div className="center-heading"><Eyebrow>WORK THAT MEANS SOMETHING</Eyebrow><h2>A place to care.<br /><em>A place to belong.</em></h2></div><div className="options-grid">{[{icon:HeartHandshake,title:'Meaningful work',text:'Make a real difference in someone’s everyday life.'},{icon:Users,title:'A supportive team',text:'Work with people who value kindness, respect, and one another.'},{icon:CalendarDays,title:'Flexible scheduling',text:'Talk with us about a schedule that fits your availability.'},{icon:Sprout,title:'Room to grow',text:'Build your experience and develop your caregiving skills.'}].map(({icon:Icon,title,text})=><article key={title}><Icon size={30} strokeWidth={1.4}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="section careers-details"><div className="container two-column"><div><Eyebrow>IS THIS YOU?</Eyebrow><h2>Kind. Dependable.<br /><em>Ready to make a difference.</em></h2><p className="body-copy">We’re looking for people who enjoy helping others and understand the importance of reliability, dignity, and personal connection.</p><ul className="check-list"><li><Check/>Caregiving experience preferred</li><li><Check/>Required Washington credentials, as applicable</li><li><Check/>Ability to pass a background check</li><li><Check/>Reliable transportation, when required</li><li><Check/>Basic English communication skills</li><li><Check/>A positive attitude and a caring heart</li></ul></div><div className="caregiver-panel"><h3>The everyday work of caring.</h3><p>Depending on each person’s care plan, you may help with:</p><ul className="check-list"><li><Check/>Personal care and daily routines</li><li><Check/>Companionship and favorite activities</li><li><Check/>Meal preparation and light housekeeping</li><li><Check/>Walking and mobility support</li><li><Check/>Non-medical medication reminders</li><li><Check/>Patient, consistent memory support</li></ul></div></div></section>
 <section className="care-cta" id="apply"><div className="container cta-layout"><div><p className="eyebrow light">LET’S GET TO KNOW EACH OTHER</p><h2>Your next chapter<br /><em>starts with a hello.</em></h2><p>Contact us about current caregiving opportunities. Tell us about your experience, availability, and what brings you to care.</p></div><div className="cta-actions"><a href={`mailto:${contact.email}?subject=${encodeURIComponent('Caregiving opportunities at Sisi Care')}&body=${encodeURIComponent('Hello Sisi Care,\n\nI am interested in caregiving opportunities.\n\nMy name:\nPhone number:\nCaregiving experience:\nCredentials:\nAvailability:\n\nThank you!')}`} className="button button-white">Email us about joining <ArrowUpRight size={18}/></a><a className="cta-phone" href={`tel:${contact.tel}`}><Phone size={18}/>{contact.phone}</a><span>{contact.email}</span></div></div></section>
 </>; }
