import type { Metadata } from 'next';
import Image from 'next/image';
import { Heart, ShieldCheck, Sprout, HandHeart, Check } from 'lucide-react';
import { PageIntro, Eyebrow, CareCTA, TrustStrip } from '@/components/shared';
import { Testimonials } from '@/components/testimonials';
export const metadata: Metadata = { title: 'About Us', description: 'Meet Sisi Care: a locally owned home care company built on more than 20 years of care experience, personal connection, and a commitment to Eastside families.' };
export default function About() {return <>
 <PageIntro eyebrow="A LOCAL TEAM WITH A LOT OF HEART" title="Care built on experience." emphasis="And human connection." description="Since 2014, we’ve helped seniors and adults across Bellevue and the Eastside live with comfort, dignity, and a little more joy at home." />
 <section className="section"><div className="container story-grid about-story"><div className="story-photo"><Image src="/images/founder.jpeg" fill priority sizes="(max-width: 760px) 90vw, 35vw" alt="Sisi, founder and owner of Sisi Care"/><div className="founder-label"><span>Sisi</span><small>Founder & Owner</small></div></div><div className="story-copy"><Eyebrow>OUR STORY</Eyebrow><h2>It began with<br /><em>a simple belief.</em></h2><p>Every person deserves to age with dignity, comfort, and kindness in the place they call home.</p><p>With more than 20 years of hands-on care experience and a background in psychology, our founder saw a need for a more personal approach to in-home care. In 2014, Sisi Care was established to bring that vision to life.</p><p>Today, we’re proud to be a locally owned care provider. Our work is built on lasting relationships, dependable support, and a commitment to the people and families in our community.</p><blockquote className="founder-quote">“Care is not just what we do—<br />it’s who we are.”<cite>— Sisi, Founder</cite></blockquote></div></div></section>
 <TrustStrip />
 <section className="section values-section"><div className="container"><div className="center-heading"><Eyebrow>WHAT MATTERS TO US</Eyebrow><h2>Good people.<br /><em>Shared values.</em></h2></div><div className="options-grid">{[{icon:HandHeart,title:'Dignity',text:'We respect each person’s choices, independence, and individual way of life.'},{icon:Heart,title:'Compassion',text:'We care with patience and kindness, in the big moments and the everyday ones.'},{icon:ShieldCheck,title:'Dependability',text:'Families can count on us to show up and be there when it matters.'},{icon:Sprout,title:'Connection',text:'We take time to know the person behind the care plan—their stories, wishes, and routines.'}].map(({icon:Icon,title,text}) => <article key={title}><Icon size={30} strokeWidth={1.4}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="section caregiver-section"><div className="container two-column"><div><Eyebrow>THE PEOPLE WHO MAKE IT POSSIBLE</Eyebrow><h2>A caring team.<br /><em>A familiar face.</em></h2><p className="body-copy">Our caregivers are at the heart of Sisi Care. We carefully select and support people who share our commitment to thoughtful, dependable care.</p></div><div className="caregiver-panel"><ShieldCheck size={37} strokeWidth={1.3}/><h3>Care you can feel confident in.</h3><ul className="check-list"><li><Check/>Carefully screened and background checked</li><li><Check/>Trained and experienced in senior care</li><li><Check/>Licensed nursing assistants and home care aides</li><li><Check/>Ongoing support and supervision</li><li><Check/>A state-licensed, insured, and bonded agency</li></ul></div></div></section>
 <Testimonials /><CareCTA />
 </>;}
