// Original letters from the customer folder. Identical copies are shown once.
// Excerpts are transcribed from the corresponding original images.
export const customerLetters = [
  {
    id: 'letter-01',
    title: 'Letter from Robert H. Campbell',
    src: '/images/customer-letters/letter-01.jpeg',
    thumbnail: '/images/customer-letters/letter-01.webp',
    width: 1536,
    height: 2048,
    author: 'Robert H. Campbell',
    kind: 'Letter of recommendation',
    excerpt:
      'My siblings, children and grandchildren all love Tsegi and count her as a dear friend.',
  },
  {
    id: 'letter-02',
    title: 'Letter from Susan · Mann & Metter families',
    src: '/images/customer-letters/letter-02.jpeg',
    thumbnail: '/images/customer-letters/letter-02.webp',
    width: 1536,
    height: 2048,
    author: 'Susan · Mann & Metter families',
    kind: 'A family’s thank-you',
    excerpt: 'We all feel tremendous respect and appreciation for each of you.',
  },
  {
    id: 'letter-03',
    title: 'Letter from The Thomas family',
    src: '/images/customer-letters/letter-03.jpeg',
    thumbnail: '/images/customer-letters/letter-03.webp',
    width: 1536,
    height: 2048,
    author: 'The Thomas family',
    kind: 'Letter of recommendation',
    excerpt:
      'The level of care that our parents received from Sisi Care was extraordinary. Our level of confidence in them was extremely high.',
  },
  {
    id: 'letter-04',
    title: 'Letter from Nancy Thomas Uhrich',
    src: '/images/customer-letters/letter-04.jpeg',
    thumbnail: '/images/customer-letters/letter-04.webp',
    width: 1536,
    height: 2048,
    author: 'Nancy Thomas Uhrich',
    kind: 'A handwritten thank-you',
    excerpt:
      'Thank you Mina and Amy with all our hearts for all your help and loving care of our parents.',
  },
  {
    id: 'letter-05',
    title: 'Letter from Allyn Warner',
    src: '/images/customer-letters/letter-05.jpeg',
    thumbnail: '/images/customer-letters/letter-05.webp',
    width: 1536,
    height: 2048,
    author: 'Allyn Warner',
    kind: 'A handwritten thank-you',
    excerpt:
      'I just wanted to take another opportunity to thank you for the kind and wonderful care that you have been giving my mother.',
  },
  {
    id: 'letter-06',
    title: 'Letter from Ann',
    src: '/images/customer-letters/letter-06.jpeg',
    thumbnail: '/images/customer-letters/letter-06.webp',
    width: 1536,
    height: 2048,
    author: 'Ann',
    kind: 'A handwritten thank-you',
    excerpt: 'She loved your sweet kindness & always felt so comfortable in your care.',
  },
  {
    id: 'letter-07',
    title: 'Letter from Bill Denman',
    src: '/images/customer-letters/letter-07.jpeg',
    thumbnail: '/images/customer-letters/letter-07.webp',
    width: 1536,
    height: 2048,
    author: 'Bill Denman',
    kind: 'A handwritten thank-you',
    excerpt:
      'Not only a friend to Mom but a caregiver with a special touch and attention to detail.',
  },
  {
    id: 'letter-08',
    title: 'Letter from Paul’s family',
    src: '/images/customer-letters/letter-08.jpeg',
    thumbnail: '/images/customer-letters/letter-08.webp',
    width: 1536,
    height: 2048,
    author: 'Paul’s family',
    kind: 'A handwritten thank-you',
    excerpt:
      'Both Paul and I have appreciated your compassionate care for Paul. You have made things a lot easier for us.',
  },
  {
    id: 'letter-09',
    title: 'Letter from Barbara',
    src: '/images/customer-letters/letter-09.jpeg',
    thumbnail: '/images/customer-letters/letter-09.webp',
    width: 1536,
    height: 2048,
    author: 'Barbara',
    kind: 'A handwritten thank-you',
    excerpt: 'You and your team are so wonderful!',
  },
  {
    id: 'letter-10',
    title: 'Letter from Susan',
    src: '/images/customer-letters/letter-10.jpeg',
    thumbnail: '/images/customer-letters/letter-10.webp',
    width: 1536,
    height: 2048,
    author: 'Susan',
    kind: 'A handwritten thank-you',
    excerpt:
      'Warm thanks for your caring and professional leadership. You & your team are incredible & we’re all so very grateful.',
  },
] as const;
